# ConfigMap para variáveis de ambiente não sensíveis
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
   POSTGRES_DB: paotheon
   POSTGRES_USER: admin
   
---
# Secret para variáveis sensíveis
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
spec:
type: Opaque
data:
  POSTGRES_PASSWORD: c2VjcmV0 # "secret" codificado em Base64
---
# Deployment para o PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres:17.5
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
           secretKeyRef:
               name: postgres-secret
               key: POSTGRES_PASSWORD
---
